networks:
  lachaudiere.net:
    driver: bridge

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./lachaudiere.core:/var/php
    networks:
      - lachaudiere.net
    working_dir: /var/php
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public /var/php/public/index.php"
    tty: true

  web-client:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./lachaudiere.web:/usr/share/nginx/html:ro
    networks:
      - lachaudiere.net

  sql:
    image: mariadb:11.3.2
    env_file:
      - .database_env
    ports:
      - "3306:3306"
    networks:
      lachaudiere.net:
        aliases:
          - sql.db
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    networks:
      - lachaudiere.net

volumes:
  db_data: