networks:
  lachaudiere.net:
    driver: bridge

services:
  app:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - "12345:80"
    volumes:
      - ./lachaudiere/:/var/php
      - ./images/img:/var/php/public/img
    working_dir: /var/php/src
    networks:
      - lachaudiere.net
    depends_on:
      - sql
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"
  
  web-client:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./lachaudiere.web:/usr/share/nginx/html:ro
    networks:
      - lachaudiere.net

  sql:
    image: mariadb:latest
    env_file:
      - .database_env
    ports:
      - "3306:3306"
    networks:
      lachaudiere.net:
        aliases:
          - sql.db
    volumes:
      - ./db_data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "12346:8080"
    networks:
      - lachaudiere.net

  web:
    image: nginx:alpine
    ports:
      - "12347:80"
    volumes:
      - ./lachaudiere.web:/usr/share/nginx/html:ro
    networks:
      - lachaudiere.net