networks:
  lachaudiere.net:
    driver: bridge

services:
  app:
    container_name: lachaudiere-app
    build:
      context: build
      dockerfile: Dockerfile
    ports:
      - "12345:80"
    volumes:
      - ./lachaudiere/:/var/php
    working_dir: /var/php/src
    networks:
      - lachaudiere.net
    depends_on:
      - sql
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"
    restart: unless-stopped

  sql:
    container_name: lachaudiere-sql
    image: mariadb:11.3
    env_file:
      - .database_env
    ports:
      - "3306:3306"
    networks:
      lachaudiere.net:
        aliases:
          - sql.db
    volumes:
      - lachaudiere_db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped

  adminer:
    container_name: lachaudiere-adminer
    image: adminer:4.8.1
    ports:
      - "12346:8080"
    networks:
      - lachaudiere.net
    restart: unless-stopped

  web:
    container_name: lachaudiere-web
    image: nginx:1.25-alpine
    ports:
      - "12347:80"
    volumes:
      - ./lachaudiere.web:/usr/share/nginx/html:ro
    networks:
      - lachaudiere.net
    restart: unless-stopped

volumes:
  lachaudiere_db_data: